# Generated by Django 6.0.2 on 2026-03-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salaryperiod',
            unique_together={('month', 'year')},
        ),
        migrations.RemoveField(
            model_name='salaryperiod',
            name='owner',
        ),
    ]
