# Generated by Django 6.0.2 on 2026-03-03 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='owner',
        ),
    ]
